const fs = require('fs');
const path = require('path');

const bnFaqs = [
  {
    "question": "শেফ কোর্স শেষ করে কেমন চাকরি পাওয়া যায়?",
    "seoAnswer": "শেফ কোর্স শেষ করে আপনি দেশ ও বিদেশের পাঁচ তারকা হোটেল, রিসোর্ট, ক্রুজ শিপ এবং প্রিমিয়াম রেস্তোরাঁয় কমি শেফ, ডেমো শেফ বা পেস্ট্রি শেফ হিসেবে চাকরি পেতে পারেন। শুরুতে এন্ট্রি-লেভেল পদে যোগ দিলেও ২-৩ বছরের মধ্যে শেফ ডি পার্টি বা সু-শেফ পদে পদোন্নতি পাওয়া সম্ভব। এছাড়া নিজস্ব ক্যাফে বা হোম বেকারি ব্যবসা শুরু করার সুযোগও রয়েছে।",
    "fullAnswer": "প্রফেশনাল শেফ কোর্স সফলভাবে সম্পন্ন করার পর হসপিটালিটি এবং ফুড সার্ভিস সেক্টরে চাকরির বিপুল ক্ষেত্র উন্মোচিত হয়। বাংলাদেশে আন্তর্জাতিক মানের পাঁচ তারকা হোটেল যেমন রেনেসাঁ ঢাকা, দ্য ওয়েস্টিন, রেডিসন ব্লু এবং প্যান প্যাসিফিক সোনারগাঁওয়ে ইন্টার্নশিপ ও স্থায়ী শেফ পদের সুযোগ রয়েছে। প্রথম দিকে ক্যারিয়ার শুরু হয় অ্যাসিস্ট্যান্ট শেফ বা কমি-৩ (Commis-III) হিসেবে, যেখানে মূল কাজ হয় কিচেনের বেসিক প্রিপারেশন বা প্রিপ-ওয়ার্ক পরিচালনা করা। আপনার কাজের দক্ষতা, নিষ্ঠা ও কিচেন শৃঙ্খলার ওপর ভিত্তি করে পরবর্তী কয়েক বছরে ডেমি শেফ ডি পার্টি (Demi-CDP), শেফ ডি পার্টি (CDP), এবং পরবর্তীতে সু-শেফ (Sous Chef) বা এক্সিকিউটিভ শেফ (Executive Chef) হিসেবে পদোন্নতি হতে পারে। বিশ্বজুড়ে, বিশেষ করে মধ্যপ্রাচ্যের (দুবাই, রিয়াদ, দোহা) বিলাসবহুল হোটেলগুলোতে এবং ইউরোপের বিভিন্ন রেস্টুরেন্টে বাংলাদেশী সার্টিফাইড শেফদের ব্যাপক চাহিদা রয়েছে। তাছাড়া আন্তর্জাতিক ক্রুজ লাইনারগুলোতে উচ্চ বেতনে কাজ করার সুযোগ তৈরি হয়। যারা সরাসরি চাকরি করতে চান না, তারা কস্টিং ও মেনু প্ল্যানিংয়ের জ্ঞান কাজে লাগিয়ে নিজস্ব রেস্তোরাঁ, ক্লাউড কিচেন বা হোম বেকিং ব্যবসা চালু করে লাভজনক উদ্যোক্তা হতে পারেন।"
  },
  {
    "question": "ঢাকায় শেফ কোর্সের খরচ কত টাকা?",
    "seoAnswer": "ঢাকায় সিআইবি (CIB) প্রফেশনাল শেফ কোর্সের মোট ফি ৪৪,০০০ টাকা। এই ফি-র মধ্যে সমস্ত ল্যাব খরচ, প্রিমিয়াম কন্টিনেন্টাল কাঁচামাল এবং একটি প্রফেশনাল শেফ কিট (ইউনিফর্ম, কাটিং বোর্ড ও নাইফ) অন্তর্ভুক্ত রয়েছে। ভর্তির সময় ১৬,০০০ টাকা পরিশোধ করে বাকি ২৮,০০০ টাকা সহজ কিস্তিতে পরিশোধ করা সম্ভব, কোনো লুকানো চার্জ নেই।",
    "fullAnswer": "ঢাকায় মানসম্পন্ন প্রফেশনাল শেফ কোর্সের খরচ সাধারণত প্রতিষ্ঠানভেদে ভিন্ন হয়ে থাকে, তবে কালিনারি ইনস্টিটিউট অব বাংলাদেশ (সিআইবি) ধানমন্ডি ক্যাম্পাসে এর মোট খরচ ৪৪,০০০ টাকা। আমরা আমাদের শিক্ষার্থীদের আর্থিক সুবিধার কথা বিবেচনা করে ৩টি সহজ কিস্তির ব্যবস্থা রেখেছি। ভর্তির দিন প্রথম কিস্তিতে ১৬,০০০ টাকা দিয়ে সিট বুক করতে হয়। বাকি ২৮,০০০ টাকা সমান দুটি কিস্তিতে (প্রতিটি ১৪,০০০ টাকা) প্রথম ও দ্বিতীয় মাসের শেষে পরিশোধ করা যায়। অনেক সাধারণ রান্নার স্কুলে ভর্তির পর ল্যাব ফি বা উপাদান ক্রয়ের জন্য অতিরিক্ত অর্থ দাবি করা হয়, কিন্তু সিআইবি-তে কড়া নির্দেশনা রয়েছে যে ৪৪,০০০ টাকার বাইরে আর একটি টাকাও নেওয়া হবে না। এই ফি-র মধ্যেই বিশ্বমানের প্রিমিয়াম উপকরণ (যেমন বিদেশী চিজ, স্যামন ফিশ, থাই হার্বস), প্রফেশনাল ব্র্যান্ডেড ইউনিফর্ম, কমার্শিয়াল কাটিং বোর্ড এবং প্রফেশনাল শেফ নাইফ সেট অন্তর্ভুক্ত রয়েছে। আমাদের এনএসডিএ পরীক্ষা ফি এবং সরকারি সনদের আনুষঙ্গিক খরচও এর মধ্যে অন্তর্ভুক্ত থাকে, যা সিআইবি-কে ঢাকার সবচেয়ে সাশ্রয়ী ও প্রিমিয়াম কালিনারি একাডেমি হিসেবে প্রতিষ্ঠিত করেছে।"
  },
  {
    "question": "মেয়েদের জন্য কোন শেফ কোর্স ভালো?",
    "seoAnswer": "মেয়েদের জন্য সিআইবি-র ৬ মাস মেয়াদী প্রফেশনাল শেফ কোর্স এবং বেকিং অ্যান্ড পেস্ট্রি শর্ট কোর্স সবচেয়ে বেশি উপযোগী। আমাদের ধানমন্ডি ক্যাম্পাসে অত্যন্ত নিরাপদ, সম্মানজনক ও সুরক্ষিত পরিবেশে সহশিক্ষা ব্যাচ পরিচালনা করা হয়। এই কোর্সগুলো সম্পন্ন করে মেয়েরা কমার্শিয়াল কিচেনে সফল ক্যারিয়ার বা নিজস্ব হোম বেকিং ও ক্যাটারিং ব্যবসা শুরু করতে পারেন।",
    "fullAnswer": "মেয়েদের জন্য কালিনারি আর্টসে ক্যারিয়ার গড়া এখন আগের চেয়ে অনেক সহজ ও সম্ভাবনাময়। সিআইবি (CIB)-তে মেয়েদের জন্য ৬ মাসের 'প্রফেশনাল শেফ কোর্স' এবং বিশেষায়িত 'বেকিং অ্যান্ড পেস্ট্রি আর্টস শর্ট কোর্স' অত্যন্ত জনপ্রিয়। আমাদের ধানমন্ডি ক্যাম্পাসে মেয়েদের নিরাপত্তা ও স্বাচ্ছন্দ্যকে সর্বোচ্চ অগ্রাধিকার দেওয়া হয়। সম্পূর্ণ কিচেন ল্যাবটি সিসিটিভি ক্যামেরা দ্বারা নিয়ন্ত্রিত এবং এখানে পেশাদার কর্পোরেট কিচেন সংস্কৃতি বজায় রাখা হয়, যেখানে যেকোনো ধরণের অসদাচরণ বা অনৈতিক আচরণের বিরুদ্ধে জিরো টলারেন্স নীতি রয়েছে। এই কোর্সগুলোতে তাত্ত্বিক ক্লাসের পাশাপাশি ১০০% প্র্যাকটিক্যাল ল্যাব সেশন করানো হয়, যা মেয়েদের কমার্শিয়াল কিচেনের উচ্চ গতিশীল কাজের সাথে খাপ খাওয়াতে সাহায্য করে। অনেক নারী শিক্ষার্থী কোর্স শেষ করে দেশের শীর্ষ পাঁচ তারকা হোটেলে সফলভাবে কাজ করছেন। এছাড়াও যারা ঘরোয়াভাবে স্বাবলম্বী হতে চান, তারা আমাদের বেকিং কোর্সের সঠিক কস্টিং, হাইজিন স্ট্যান্ডার্ড এবং কেক ডেকোরেশন শিখে লাভজনক হোম-বেসড কেকের ব্যবসা বা ক্যাটারিং শুরু করতে পারেন। সিআইবি মেয়েদের স্বাবলম্বী করতে ক্যারিয়ার সাপোর্ট এবং বিশেষ উদ্যোক্তা নির্দেশিকা প্রদান করে থাকে।"
  },
  {
    "question": "শেফ কোর্স করার পর বিদেশ যাওয়ার উপায় কি?",
    "seoAnswer": "শেফ কোর্স সম্পন্ন করে সরকারি এনএসডিএ সার্টিফিকেট ও আইএসও-এইচএসিসিপি সনদ নিন। এরপর ৩/৫ তারকা হোটেলে ১-২ বছরের অভিজ্ঞতা অর্জন করুন। বেসিক ইংরেজি বা সংশ্লিষ্ট দেশের ভাষা শিখে Ami Probashi পোর্টাল ও অনুমোদিত রিক্রুটিং এজেন্সির মাধ্যমে কাজের ভিসার আবেদন করুন। সিআইবি শিক্ষার্থীদের প্লেসমেন্ট সেলের মাধ্যমে সরাসরি গাইড করে থাকে।",
    "fullAnswer": "শেফ কোর্স শেষ করার পর বিদেশে সফল কালিনারি ক্যারিয়ার গড়ার জন্য একটি সুনির্দিষ্ট আইনি প্রক্রিয়া অনুসরণ করতে হয়। প্রথম ধাপ হলো সিআইবি-র মতো বিশ্বস্ত প্রতিষ্ঠান থেকে প্রশিক্ষণ নিয়ে প্রধানমন্ত্রীর কার্যালয়ের অধীনে এনএসডিএ (NSDA) লেভেল ২ বা ৩ সার্টিফিকেট এবং আন্তর্জাতিক মানের ISO ২২০০০ বা HACCP ফুড সেফটি সনদ অর্জন করা। দ্বিতীয়ত, তাত্ত্বিক জ্ঞানকে সমৃদ্ধ করতে এবং কাজের গতি বাড়াতে স্থানীয় পাঁচ তারকা হোটেল বা ভালো প্রিমিয়াম রেস্তোরাঁয় অন্তত ১ থেকে ২ বছরের বাস্তব কাজের অভিজ্ঞতা অর্জন করতে হবে। তৃতীয়ত, গন্তব্য দেশের ওপর নির্ভর করে ভাষা দক্ষতা বাড়াতে হবে; যেমন মধ্যপ্রাচ্যের জন্য বেসিক ইংরেজি জানলেই চলে, তবে জার্মানি, অস্ট্রেলিয়া বা যুক্তরাজ্যের মতো দেশে স্কিল্ড ওয়ার্কার ভিসার জন্য আইইএলটিএস (IELTS) ন্যূনতম ৫.৫ স্কোর বা সংশ্লিষ্ট দেশের ভাষা (যেমন জার্মান A2/B1) প্রয়োজন। এরপর, সরকারি পোর্টাল 'আমি প্রবাসী' অ্যাপে নিবন্ধন করতে হবে এবং প্রবাসী কল্যাণ মন্ত্রণালয় ও বিএমইটি (BMET) অনুমোদিত বৈধ রিক্রুটিং এজেন্সির মাধ্যমে কাঙ্ক্ষিত চাকরির জন্য আবেদন করতে হবে। সিআইবি-র ডেডিকেটেড প্লেসমেন্ট সেল আমাদের শিক্ষার্থীদের সিবি রিভিউ, ভিডিও পোর্টফোলিও তৈরি এবং আন্তর্জাতিক রিক্রুটারদের সাথে ইন্টারভিউয়ের জন্য যাবতীয় সহায়তা প্রদান করে থাকে।"
  },
  {
    "question": "শেফ হিসেবে ক্যারিয়ার গড়তে কতদিন লাগে?",
    "seoAnswer": "শেফ হিসেবে ক্যারিয়ারের মূল ফাউন্ডেশন তৈরি করতে ৬ মাস সময় লাগে (২ মাস কিচেন ল্যাব প্র্যাকটিক্যাল ও ৪ মাস ৫-স্টার হোটেল ইন্টার্নশিপ)। তবে প্রফেশনাল কিচেনে নিজের শক্ত অবস্থান তৈরি করতে এবং ভালো বেতনে সিনিয়র পদে পৌঁছাতে সাধারণত ৩ থেকে ৫ বছরের বাস্তব কাজের অভিজ্ঞতার প্রয়োজন হয়।",
    "fullAnswer": "শেফ হিসেবে ক্যারিয়ার গড়ার যাত্রাটি ধারাবাহিক পরিশ্রম এবং দক্ষতা অর্জনের বিষয়। সিআইবি-তে আপনার ক্যারিয়ারের মূল ফাউন্ডেশন তৈরি করতে ৬ মাস সময় লাগবে। এর মধ্যে প্রথম ২ মাস আমাদের ল্যাবে সপ্তাহে ৩ দিন করে নিবিড় ব্যবহারিক ক্লাস নেওয়া হবে, যেখানে ছুরি চালানো থেকে শুরু করে গ্লোবাল কুইজিন ও মেনু ইঞ্জিনিয়ারিং শেখানো হয়। পরবর্তী ৪ মাস আপনাকে একটি পাঁচ তারকা হোটেলে বাস্তব কাজের প্রশিক্ষণের জন্য ইন্টার্নশিপে পাঠানো হবে। এই ৬ মাস শেষে আপনি একজন প্রত্যয়িত 'কমি শেফ' হিসেবে চাকরি শুরু করার যোগ্যতা পাবেন। এরপর এন্ট্রি-লেভেল থেকে শুরু করে কিচেনের বিভিন্ন সেকশন (যেমন হট কিচেন, কোল্ড কিচেন, সস সেকশন, পেস্ট্রি) পরিচালনা করে দক্ষ হতে এবং সিনিয়র পজিশন যেমন 'শেফ ডি পার্টি' (CDP) হতে সাধারণত আরও ৩ থেকে ৪ বছর কঠোর পরিশ্রম করতে হবে। হসপিটালিটি সেক্টরে কাজের গতি, উদ্ভাবনী শক্তি এবং শৃঙ্খলার ওপর ভিত্তি করে আপনার পদোন্নতি নির্ধারিত হয়, যা আপনাকে ৫ থেকে ৭ বছরের মধ্যে একজন এক্সিকিউটিভ শেফ বা কিচেন ম্যানেজার হিসেবে প্রতিষ্ঠিত করতে পারে।"
  },
  {
    "question": "শেফদের কাজের সময় কেমন হয়?",
    "seoAnswer": "প্রফেশনাল কিচেনে সাধারণত দৈনিক ৮ থেকে ১০ ঘণ্টা শিফটিং ডিউটি থাকে। হসপিটালিটি সেক্টর ২৪/৭ চালু থাকায় মর্নিং, আফটারনুন ও নাইট শিফটে কাজ করতে হয়। উৎসব বা ব্যস্ত ছুটির দিনগুলোতে কাজের চাপ কিছুটা বেশি থাকে এবং কাজের পরিবেশ বেশ গতিশীল ও সুশৃঙ্খল হয়ে থাকে।",
    "fullAnswer": "হসপিটালিটি বা পাঁচ তারকা কিচেনের কাজের সময় সাধারণ ৯টা-৫টার অফিসের মতো নয়। এখানে কাজ মূলত শিফট ভিত্তিক হয়ে থাকে এবং দৈনিক শিফটের সময়কাল সাধারণত ৮ থেকে ১০ ঘণ্টা। যেহেতু রেস্তোরাঁ ও হোটেল ২৪ ঘণ্টা চালু থাকে, তাই কিচেন কর্মীদের রোটেশনাল শিফটে কাজ করতে হয়—যার মধ্যে রয়েছে মর্নিং শিফট (সকাল ৬টা থেকে দুপুর ৩টা), ইভনিং শিফট (দুপুর ২টা থেকে রাত ১১টা), এবং বিশেষ ক্ষেত্রে নাইট বা ওটি শিফট। কাজের দিনগুলোতে সাধারণত একটি নির্দিষ্ট উইকলি অফ বা সাপ্তাহিক ছুটি পাওয়া যায়, যা সপ্তাহের যেকোনো দিন হতে পারে। উৎসবের মৌসুমে যেমন রমজান, ঈদ, নববর্ষ বা বড় ডিনারের সময় কাজের চাপ কিছুটা বৃদ্ধি পায়, তবে এর বিনিময়ে ওভারটাইম ভাতা এবং অতিরিক্ত সার্ভিস চার্জ বোনাস পাওয়া যায়। প্রফেশনাল কিচেনের কাজের পরিবেশ অত্যন্ত গতিশীল এবং এখানে সামরিক শৃঙ্খলার মতো টিমওয়ার্ক বজায় রাখতে হয়। সিআইবি-তে আমরা আমাদের প্র্যাকটিক্যাল ক্লাসের মাধ্যমে শিক্ষার্থীদের এই পেশাদার কিচেন শিডিউল এবং সময়ের গুরুত্ব সম্পর্কে বাস্তব ধারণা প্রদান করি।"
  },
  {
    "question": "শেফ কোর্সে ভর্তির জন্য কী কী ডকুমেন্ট লাগে?",
    "seoAnswer": "সিআইবি প্রফেশনাল শেফ কোর্সে ভর্তির জন্য আপনার নূন্যতম শিক্ষাগত যোগ্যতার সনদ (এসএসসি/এইচএসসি বা সমমানের সার্টিফিকেট), জাতীয় পরিচয়পত্র (NID) বা জন্ম সনদের কপি, এবং ২ কপি পাসপোর্ট সাইজের রঙিন ছবি লাগবে। পূর্বে কোনো রান্নার অভিজ্ঞতার কাগজপত্রের প্রয়োজন নেই।",
    "fullAnswer": "কালিনারি ইনস্টিটিউট অব বাংলাদেশ (CIB)-এ ভর্তির প্রক্রিয়াটি খুবই সহজ ও সুশৃঙ্খল। আমাদের প্রফেশনাল বা শর্ট কোর্সে ভর্তি হতে চাইলে শিক্ষার্থীদের কিছু মৌলিক কাগজপত্র জমা দিতে হয়। এর মধ্যে রয়েছে: নূন্যতম এসএসসি বা এইচএসসি পাশের সার্টিফিকেট বা মার্কশিটের সত্যায়িত ফটোকপি (অথবা সমমানের যেকোনো শিক্ষাগত যোগ্যতার প্রমাণপত্র), জাতীয় পরিচয়পত্রের (NID Card) ফটোকপি (যদি আইডি কার্ড না থাকে তবে ডিজিটাল জন্ম নিবন্ধন সনদের কপি গ্রহণযোগ্য), এবং সদ্য তোলা ২ কপি পাসপোর্ট সাইজের ল্যাব প্রিন্ট রঙিন ছবি। পূর্বে কোনো রান্নার কাজের অভিজ্ঞতা বা কালিনারি স্কুলিংয়ের সার্টিফিকেটের প্রয়োজন নেই, কারণ আমরা সম্পূর্ণ শূন্য থেকে শিক্ষা শুরু করি। যেকোনো ব্যাকগ্রাউন্ড (যেমন বিজ্ঞান, মানবিক, ব্যবসায় শিক্ষা বা মাদরাসা) থেকে আসা শিক্ষার্থীরা সরাসরি ভর্তি হতে পারেন। এই প্রয়োজনীয় কাগজপত্র নিয়ে ধানমন্ডি ক্যাম্পাসে সশরীরে এসে বা আমাদের অফিশিয়াল ওয়েবসাইটের মাধ্যমে অনলাইন ফরম পূরণ করে সহজেই আপনার ভর্তি সম্পন্ন করতে পারেন।"
  },
  {
    "question": "শেফ ট্রেনিং শেষে সার্টিফিকেট পেতে কতদিন লাগে?",
    "seoAnswer": "সিআইবি-র প্রাতিষ্ঠানিক কোর্স সমাপ্তির সার্টিফিকেট এবং পরীক্ষার মার্কশিট মূল কোর্স সম্পন্ন হওয়ার ৭ থেকে ১০ দিনের মধ্যে প্রদান করা হয়। তবে সরকারি এনএসডিএ (NSDA) সার্টিফিকেট পাওয়ার সময়কাল জাতীয় মূল্যায়ন ও পরীক্ষার বোর্ড অনুমোদনের ওপর নির্ভর করে সাধারণত ১ থেকে ২ মাস পর্যন্ত হতে পারে।",
    "fullAnswer": "কোর্স সমাপ্তির পর সার্টিফিকেট পাওয়ার প্রক্রিয়াটি স্বচ্ছ এবং দ্রুত। সিআইবি-র ২ মাসের প্র্যাকটিক্যাল কিচেন ল্যাব ক্লাস ও পরীক্ষা শেষ করার পর, আমরা ৭ থেকে ১০ কর্মদিবসের মধ্যে প্রাতিষ্ঠানিক কোর্স সমাপ্তি সনদ ও গ্রেড শিট শিক্ষার্থীদের হাতে তুলে দিই। এরপর যখন শিক্ষার্থীরা ৫-স্টার হোটেলে ৪ মাসের অন-দ্য-জব ইন্টার্নশিপ সম্পন্ন করেন, তখন সেই নির্দিষ্ট হোটেল থেকে একটি অফিশিয়াল ইন্টার্নশিপ এক্সপেরিয়েন্স সার্টিফিকেট প্রদান করা হয়। অন্যদিকে, সরকারি এনএসডিএ (NSDA) লেভেল সার্টিফিকেটের জন্য শিক্ষার্থীদের একটি ব্যবহারিক মূল্যায়নে অংশ নিতে হয় যা সিআইবি ক্যাম্পাসে সরকারি অ্যাসিসরদের উপস্থিতিতে অনুষ্ঠিত হয়। এই পরীক্ষার ফলাফল ও বোর্ড অনুমোদন প্রক্রিয়া শেষ করে চূড়ান্ত সরকারি ডিজিটাল ও হার্ডকপি সার্টিফিকেট পেতে সাধারণত পরীক্ষার দিন থেকে ১ থেকে ২ মাস সময় লাগে। এই সরকারি সনদটি সরাসরি অনলাইন ডেটাবেজে ভেরিফাই করা যায়, যা বিদেশের চাকরির ভিসার জন্য অত্যন্ত শক্তিশালী একটি নথি।"
  },
  {
    "question": "শেফ কোর্স কি অনলাইনে করা যায়?",
    "seoAnswer": "প্রফেশনাল শেফ কোর্স পুরোপুরি অনলাইনে করা সম্ভব নয়, কারণ কালিনারি আর্টস একটি সম্পূর্ণ ব্যবহারিক বিষয় যা সরাসরি কমার্শিয়াল কিচেনে ছুরি চালানো ও রান্নার মাধ্যমে শিখতে হয়। তবে সিআইবি তাত্ত্বিক ও ফুড সেফটি ক্লাসগুলো বিশেষ ক্ষেত্রে হাইব্রিড মডেলে অনলাইনে নেওয়ার ব্যবস্থা করে থাকে।",
    "fullAnswer": "কালিনারি আর্টস বা পেশাদার রান্না হলো একটি সম্পূর্ণ প্র্যাকটিক্যাল বা ব্যবহারিক শিল্প। অনলাইনে রেসিপির ভিডিও দেখা সম্ভব হলেও, সঠিক উপায়ে ছুরি চালানো (Knife Skills), ফ্লেভার ব্যালেন্সিং, কমার্শিয়াল ওভেন পরিচালনা, এবং হাই-প্রেসার কিচেনের তাপমাত্রা নিয়ন্ত্রণ করা অনলাইন ক্লাসের মাধ্যমে কখনোই শেখা সম্ভব নয়। তাই প্রফেশনাল শেফ হওয়ার জন্য ল্যাবে সরাসরি ক্লাসের কোনো বিকল্প নেই। সিআইবি ধানমন্ডি ক্যাম্পাসে শিক্ষার্থীদের ১০০% কমার্শিয়াল-গ্রেড কিচেন ওয়ার্কস্টেশন এবং প্রয়োজনীয় আধুনিক যন্ত্রপাতি সরবরাহ করা হয়, যেখানে শিক্ষার্থীরা সরাসরি মেন্টরদের তত্ত্বাবধানে প্রতিটি পদ নিজে রান্না করেন। তবে, আমরা আমাদের থিওরিটিক্যাল পার্ট যেমন—মেনু কস্টিং, রেসিপি রাইটিং, কিচেন ম্যানেজমেন্ট এবং বেসিক ফুড সেফটি (HACCP) সংক্রান্ত লেকচারগুলো শিক্ষার্থীদের সুবিধার জন্য কিছু বিশেষ ক্ষেত্রে অনলাইন বা হাইব্রিড মডেলে পরিচালনা করে থাকি। পরিপূর্ণ পেশাদার শেফ হতে চাইলে আপনাকে অবশ্যই সরাসরি বাস্তব প্রশিক্ষণে অংশ নিতে হবে।"
  },
  {
    "question": "ঢাকার বাইরে থেকে এসে শেফ কোর্স করলে থাকার ব্যবস্থা আছে?",
    "seoAnswer": "সিআইবি-র নিজস্ব সরাসরি হোস্টেল সুবিধা নেই, তবে ঢাকার বাইরে থেকে আসা শিক্ষার্থীদের জন্য ধানমন্ডি ও কলাবাগান ক্যাম্পাসের আশেপাশে সাশ্রয়ী মূল্যে নিরাপদ মেস বা পেয়িং গেস্ট থাকার ব্যবস্থা খুঁজে পেতে আমরা সম্পূর্ণ তথ্যগত ও প্রশাসনিক সহায়তা প্রদান করে থাকি।",
    "fullAnswer": "কালিনারি ইনস্টিটিউট অব বাংলাদেশ (সিআইবি) দেশের প্রতিটি প্রান্ত থেকে আসা শিক্ষার্থীদের স্বাগত জানায়। যদিও আমাদের নিজস্ব কোনো আবাসিক হোস্টেল নেই, তবে আমাদের একটি ডেডিকেটেড স্টুডেন্ট সাপোর্ট টিম রয়েছে যা ঢাকার বাইরে থেকে আসা শিক্ষার্থীদের ক্যাম্পাসের খুব কাছে নিরাপদ এবং সাশ্রয়ী আবাসন খুঁজে পেতে সহায়তা করে। ধানমন্ডি ও কলাবাগান এলাকায় প্রচুর ছাত্র হোস্টেল, মেস এবং পেয়িং গেস্টের সুযোগ রয়েছে, যেখানে মাসিক ৩,০০০ থেকে ৬,০০০ টাকার মধ্যে থাকা ও খাওয়ার ব্যবস্থা পাওয়া যায়। ভর্তির সময় আমাদের স্টুডেন্ট উইং শিক্ষার্থীদের এই সমস্ত হোস্টেলের ঠিকানা, কন্টাক্ট নম্বর এবং দরদামের তথ্য দিয়ে সহায়তা করে, যাতে করে খুব দ্রুত ও নিরাপদে তারা থাকার ব্যবস্থা করতে পারেন। ল্যাবের ক্লাসগুলো সপ্তাহে ৩ দিন হওয়ায় ঢাকার বাইরে থেকে এসেও অনেকে ঢাকায় পার্ট-টাইম কাজ বা পড়াশোনার পাশাপাশি স্বাচ্ছন্দ্যে এই কোর্স সম্পন্ন করতে পারেন।"
  },
  {
    "question": "শেফ কোর্স শেষে কত বেতন আশা করা যায়?",
    "seoAnswer": "বাংলাদেশী হসপিটালিটি সেক্টরে এন্ট্রি-লেভেল কমি শেফদের প্রারম্ভিক বেতন সাধারণত ১৫,০০০ থেকে ২৫,০০০ টাকা হয়ে থাকে, সাথে বোনাস ও সার্ভিস চার্জ যুক্ত হয়। ২-৩ বছরের অভিজ্ঞতা অর্জন করার পর প্রিমিয়াম রেস্তোরাঁগুলোতে বেতন ৩৫,০০০ থেকে ৬০,০০০ টাকা এবং বিদেশে ৬০,০০০ থেকে ১,৫০,০০০ টাকা পর্যন্ত হতে পারে।",
    "fullAnswer": "শেফ পেশায় উপার্জনের সম্ভাবনা সরাসরি আপনার ব্যবহারিক দক্ষতা এবং অভিজ্ঞতার ওপর নির্ভর করে। বাংলাদেশে কোর্স সম্পন্ন করার পর এন্ট্রি-লেভেল কমি-৩ (Commis-III) হিসেবে পাঁচ তারকা হোটেলে বেসিক সেলারি ১৫,০০০ থেকে ২৫,০০০ টাকার মধ্যে শুরু হয়। তবে এর সাথে সার্ভিস চার্জের একটি বড় অংশ যুক্ত হয়, যা কিচেন স্টাফদের মোট আয়কে প্রায় দ্বিগুণ করে দেয়। ৩ থেকে ৫ বছরের বাস্তব কিচেন অভিজ্ঞতা সম্পন্ন একজন শেফ ডি পার্টি (CDP) বাংলাদেশে প্রতি মাসে ৩৫,০০০ থেকে ৬০,০০০ টাকা আয় করতে পারেন। আন্তর্জাতিক বাজারে, বিশেষ করে মধ্যপ্রাচ্যে (দুবাই, সৌদি আরব, কাতার) বাংলাদেশী শেফদের প্রারম্ভিক বেতন করমুক্ত ৬৫,০০০ থেকে ৯৫,০০০ টাকার সমপরিমাণ হয়ে থাকে, যেখানে মালিক পক্ষ বিনামূল্যে আবাসন, খাবার, যাতায়াত এবং প্রতি বছর বিমান টিকিট সরবরাহ করে। ৫-৭ বছরের অভিজ্ঞতাসম্পন্ন হেড শেফ বা এক্সিকিউটিভ শেফদের বেতন বাংলাদেশে ১,৫০,০০০ থেকে ৪,৫০,০০০ টাকা বা তার বেশি হতে পারে। সিআইবি-র মানসম্মত প্রশিক্ষণ ও সার্টিফিকেট আপনাকে শুরু থেকেই ভালো সেলারি স্কেলে প্রবেশ করতে সাহায্য করে।"
  },
  {
    "question": "কোন বয়সে শেফ কোর্স শুরু করা উচিত?",
    "seoAnswer": "শেফ কোর্স শুরু করার জন্য আদর্শ বয়স হলো ১৬ থেকে ৩৫ বছর, কারণ এই সময়ে শারীরিক স্ট্যামিনা এবং নতুন দক্ষতা দ্রুত শেখার ক্ষমতা বেশি থাকে। তবে রান্নার ক্ষেত্রে শেখার কোনো বয়সসীমা নেই; আমাদের কোর্সগুলোতে ৪০+ বছর বয়সী অনেক শিক্ষার্থীও সফলভাবে প্রশিক্ষণ নিয়েছেন।",
    "fullAnswer": "কালিনারি আর্টস বা পেশাদার রন্ধনশিল্পে ক্যারিয়ার শুরু করার কোনো নির্দিষ্ট এবং কঠোর বয়সসীমা নেই, তবে ১৬ থেকে ৩৫ বছর বয়সকে এই কোর্স শুরু করার জন্য সবচেয়ে আদর্শ সময় বিবেচনা করা হয়। এই বয়সে তরুণদের শারীরিক স্ট্যামিনা এবং দীর্ঘক্ষণ দাঁড়িয়ে কাজ করার কায়িক ক্ষমতা বেশি থাকে, যা কমার্শিয়াল কিচেনের উচ্চ গতিশীল কাজের সাথে দ্রুত খাপ খাইয়ে নিতে সাহায্য করে। তাছাড়া নতুন রেসিপি শেখা, নাইফ কন্ট্রোল এবং ইংরেজি যোগাযোগের ভাষা আয়ত্ত করার ক্ষেত্রে তরুণরা ভালো পারফর্ম করে। তবে এর মানে এই নয় যে প্রবীণরা শেফ হতে পারবেন না। সিআইবি-তে আমাদের অনেক শিক্ষার্থী রয়েছেন যাদের বয়স ৪০ বা ৫০ বছরের ওপরে, যারা চাকরি থেকে অবসর নিয়ে বা গৃহিণী হিসেবে স্বাবলম্বী হতে এসে চমৎকারভাবে বেকিং বা কুকিং কোর্স সম্পন্ন করেছেন এবং সফলভাবে নিজেদের রেস্তোরাঁ ও ক্যাটারিং ব্যবসা পরিচালনা করছেন। আপনার মধ্যে যদি কালিনারি আর্টসের প্রতি প্যাশন এবং শৃঙ্খলা থাকে, তবে বয়স কোনো বাধা নয়।"
  },
  {
    "question": "শেফ হতে গেলে কি ইংরেজি জানা জরুরি?",
    "seoAnswer": "হ্যাঁ, শেফ হতে গেলে বেসিক ইংরেজি জানা অত্যন্ত গুরুত্বপূর্ণ। কারণ কমার্শিয়াল কিচেনের সমস্ত রেসিপি ম্যানুয়াল, ক্লাসিক্যাল কালিনারি টার্ম (যেমন ফ্রেঞ্চ টার্মস) এবং বিদেশী কাঁচামালের লেবেলগুলো ইংরেজিতে থাকে। তাছাড়া বিদেশের চাকরির ইন্টারভিউতে ইংরেজি যোগাযোগের ক্ষমতা যাচাই করা হয়।",
    "fullAnswer": "পেশাদার শেফ হওয়ার জন্য ইংরেজি ভাষার প্রাথমিক জ্ঞান থাকা অত্যন্ত প্রয়োজনীয় এবং এটি আপনার ক্যারিয়ারের বৃদ্ধির গতিকে বহুগুণ বাড়িয়ে দেয়। কমার্শিয়াল কিচেনের পরিবেশ আন্তর্জাতিক মানের হয়ে থাকে, যেখানে ব্যবহৃত সমস্ত রেসিপি ম্যানুয়াল, রান্না পরিমাপের একক, এবং ক্লাসিক্যাল কুকিং মেথড (যেমন জাঁউলিঁয়ে, শিফনড, সতে) মূলত ইংরেজিতে বা ফ্রেঞ্চ কালিনারি টার্মে লেখা হয়। পাঁচ তারকা হোটেলে কাজ করার সময় আপনাকে বিদেশী শেফ এবং ক্লায়েন্টদের সাথে যোগাযোগ করতে হবে, যা ইংরেজি ছাড়া সম্ভব নয়। বিশেষ করে যারা বিদেশে (ইউরোপ, যুক্তরাজ্য বা ক্রুজ লাইনে) কাজ করতে চান, তাদের জন্য কাজের ভিসা পেতে বেসিক ইংলিশ কমিউনিকেশন টেস্ট বা আইইএলটিএস (IELTS)-এ ন্যূনতম স্কোর প্রয়োজন হয়। সিআইবি-তে আমাদের প্র্যাকটিক্যাল ক্লাসগুলোতে তাত্ত্বিক লেকচার বাংলায় দেওয়া হলেও, আমরা সমস্ত রেসিপি শিট ও পেশাদার কিচেন টার্মিনোলজি কঠোরভাবে ইংরেজিতে শিখিয়ে থাকি, যাতে শিক্ষার্থীরা বৈশ্বিক মার্কেটের জন্য প্রস্তুত হতে পারে।"
  },
  {
    "question": "শেফ কোর্সের ক্লাসগুলো কিভাবে হয়?",
    "seoAnswer": "সিআইবি-তে শেফ কোর্সের ক্লাসগুলো সম্পূর্ণ হ্যান্ডস-অন বা ব্যবহারিক উপায়ে অনুষ্ঠিত হয়। প্রতিটি ক্লাসের শুরুতে মেন্টর রেসিপির থিওরি ও ডেমো প্রদর্শন করেন, এরপর শিক্ষার্থীরা নিজস্ব ওয়ার্কস্টেশনে মাস্টার শেফের সরাসরি তত্ত্বাবধানে নিজে হাতে প্রতিটি ডিশ তৈরি করেন এবং স্বাদের মূল্যায়ন পান।",
    "fullAnswer": "কালিনারি ইনস্টিটিউট অব বাংলাদেশ (সিআইবি)-তে ক্লাসগুলো অত্যন্ত সুশৃঙ্খল এবং বিশ্বমানের পদ্ধতিতে নেওয়া হয়। আমাদের ক্লাসগুলো মূলত ৩ ঘণ্টার সেশনে বিভক্ত। ক্লাসের প্রথম ৩০ মিনিটে মাস্টার শেফ দিনের নির্দিষ্ট রেসিপি, এর কাঁচামাল, রন্ধন বিজ্ঞান এবং প্রফেশনাল টেকনিক সম্পর্কে শিক্ষার্থীদের ব্রিফ করেন। পরবর্তী ৩০ মিনিটে শেফ নিজে হাতে রান্না করে একটি সরাসরি ডেমোনস্ট্রেশন বা ডেমো ক্লাস প্রদর্শন করেন, যেখানে প্রতিটি ধাপ এবং নাইফ স্কিল শিক্ষার্থীদের সূক্ষ্মভাবে বুঝিয়ে দেওয়া হয়। ক্লাসের বাকি ২ ঘণ্টা সম্পূর্ণ শিক্ষার্থীদের ব্যবহারিক কাজের জন্য বরাদ্দ থাকে। প্রতিটি শিক্ষার্থীকে আমাদের আধুনিক কিচেনে নিজস্ব কমার্শিয়াল গ্যাস ওভেন, নাইফ সেট এবং উপাদান সরবরাহ করা হয়, যেখানে তারা মেন্টর শেফের সরাসরি তত্ত্বাবধানে নিজ হাতে সম্পূর্ণ রেসিপিটি রান্না করেন। ক্লাস শেষে শেফ প্রতিটি শিক্ষার্থীর তৈরি ডিশের টেক্সচার, ফ্লেভার এবং প্লেটিং সরাসরি টেস্ট করে মূল্যায়ন করেন ও গঠনমূলক ফিডব্যাক দেন, যা দ্রুত শেখার জন্য অত্যন্ত কার্যকরী।"
  },
  {
    "question": "শেফ কোর্সের ফি কি কিস্তিতে পরিশোধ করা যায়?",
    "seoAnswer": "হ্যাঁ, সিআইবি-তে শেফ কোর্সের মোট ফি ৪৪,০০০ টাকা ৩টি সহজ কিস্তির মাধ্যমে পরিশোধ করা যায়। ভর্তির সময় প্রথম কিস্তিতে ১৬,০০০ টাকা দিয়ে সিট কনফার্ম করতে হয় এবং বাকি ২৮,০০০ টাকা সমান দুটি ১৪,০০০ টাকার কিস্তিতে পরবর্তী দুই মাসে পরিশোধের সুবিধা রয়েছে।",
    "fullAnswer": "আমরা বিশ্বাস করি যে আর্থিক অসচ্ছলতা কোনো শিক্ষার্থীর কালিনারি স্বপ্ন পূরণে বাধা হওয়া উচিত নয়। তাই সিআইবি-তে আমরা একটি অত্যন্ত সাশ্রয়ী এবং নমনীয় কিস্তি পেমেন্ট পলিসি চালু রেখেছি। আমাদের ৬ মাস মেয়াদী প্রফেশনাল শেফ কোর্সের সর্বমোট ফি ৪৪,০০০ টাকা (যার মধ্যে কোনো গোপন ফি বা অতিরিক্ত পরীক্ষার চার্জ নেই)। শিক্ষার্থীরা এই ফি মোট ৩টি কিস্তিতে পরিশোধ করতে পারেন: ১. প্রথম কিস্তি: ভর্তির সময় ১৬,০০০ টাকা দিয়ে নাম নিবন্ধন ও শেফ কিট সংগ্রহ করতে হয়। ২. দ্বিতীয় কিস্তি: ক্লাস শুরু হওয়ার ৩০ দিন পর অর্থাৎ প্রথম মাসের শেষে ১৪,০০০ টাকা দিতে হয়। ৩. তৃতীয় বা শেষ কিস্তি: ক্লাস শুরু হওয়ার ৬০ দিন পর অর্থাৎ দ্বিতীয় মাসের শেষে বাকি ১৪,০০০ টাকা পরিশোধ করতে হয়। এই কিস্তির টাকাগুলো নগদ ক্যাশ, ব্যাংক ডিপোজিট অথবা বিকাশ/নগদ এর মতো মোবাইল ব্যাংকিং সেবার মাধ্যমে ঘরে বসেই খুব সহজে পরিশোধ করা যায়।"
  },
  {
    "question": "শেফ কোর্সে প্র্যাকটিক্যাল কেমন হয়?",
    "seoAnswer": "সিআইবি-তে ৯৫% এর বেশি ক্লাস প্র্যাকটিক্যাল বা ব্যবহারিক হয়ে থাকে। শিক্ষার্থীরা বই বা ভিডিও দেখে নয়, বরং সরাসরি আমাদের কমার্শিয়াল কিচেন ল্যাবে তাজা কাঁচামাল যেমন স্যামন মাছ, গরুর মাংস, এশিয়ান সস এবং কন্টিনেন্টাল হার্বস নিজ হাতে প্রসেস এবং রান্না করে প্রতিটি রেসিপি আয়ত্ত করেন।",
    "fullAnswer": "রান্না শেখার একমাত্র উপায় হলো নিজে হাতে রান্না করা। সিআইবি-তে আমাদের মূল দর্শন হলো ১০০% প্র্যাকটিক্যাল লার্নিং বা হাতে-কলমে শিক্ষা। আমাদের কিচেন ল্যাবগুলো ফাইভ-স্টার হোটেলের কমার্শিয়াল কিচেনের আদলে তৈরি করা হয়েছে। প্র্যাকটিক্যাল ক্লাসে শিক্ষার্থীরা মাংস ও মাছ কাটা, সস ও স্যুপ তৈরি, থ্রি-কোর্স মিল প্রিপারেশন, ফাইন ডাইনিং প্লেটিং এবং ওভেন নিয়ন্ত্রণের মতো কাজগুলো সরাসরি নিজে করেন। আমরা শিক্ষার্থীদের কোনো থিওরি মুখস্থ করাই না; বরং প্রতিদিনের ল্যাবে স্যামন মাছ, প্রিমিয়াম চিকেন, চিংড়ি, এবং বিদেশী পনির ও সস সরবরাহ করা হয়। প্রতিটি ক্লাসে একজন স্টুডেন্ট একটি সম্পূর্ণ ইন্ডিভিজুয়াল ডিশ তৈরি করেন, কোনো গ্রুপ রান্নার সুযোগ নেই, যাতে করে সবার ব্যক্তিগত দক্ষতা নিশ্চিত হয়। অভিজ্ঞ মাস্টার শেফরা সার্বক্ষণিকভাবে শিক্ষার্থীদের পাশে দাঁড়িয়ে ভুলগুলো সংশোধন করে দেন।"
  },
  {
    "question": "শেফ কোর্স করলে কি রেস্টুরেন্ট ব্যবসা শুরু করা যায়?",
    "seoAnswer": "হ্যাঁ, শেফ কোর্স সম্পন্ন করে লাভজনক রেস্টুরেন্ট বা ক্যাফে ব্যবসা শুরু করা খুব সহজ হয়। কোর্সে রেসিপির পাশাপাশি সঠিক ফুড কস্টিং, পোরশন কন্ট্রোল, মেনু প্ল্যানিং, এবং কিচেন লে-আউট ম্যানেজমেন্ট শেখানো হয়, যা ব্যবসায় লস বা অপচয় রোধ করে লাভ নিশ্চিত করতে সাহায্য করে।",
    "fullAnswer": "একটি সফল রেস্তোরাঁ পরিচালনার পেছনে শুধু সুস্বাদু খাবার নয়, বরং সঠিক কালিনারি বিজনেস ম্যানেজমেন্ট প্রয়োজন হয়। সিআইবি-র প্রফেশনাল কোর্সে রেসিপি রান্নার পাশাপাশি কীভাবে মেনু ইঞ্জিনিয়ারিং করতে হয়, কীভাবে প্রতিটি পদের পোরশন সাইজ বা পরিমাণ নিয়ন্ত্রণ করতে হয় এবং কাঁচামালের অপচয় (Wastage) কমিয়ে ফুড কস্টিং করা হয় তা বিস্তারিত শেখানো হয়। একজন উদ্যোক্তা যদি নিজে রান্না এবং কিচেন অপারেশন বোঝেন, তবে তার কর্মচারীদের ওপর নির্ভরশীলতা অনেক কমে যায় এবং কিচেন চুরি বা লোকসান রোধ করা সহজ হয়। সিআইবি-র অনেক গ্র্যাজুয়েট বর্তমানে সফলভাবে ঢাকায় ক্যাফে, প্রিমিয়াম রেস্তোরাঁ ও ক্লাউড কিচেন চালাচ্ছেন। আমরা আমাদের শিক্ষার্থীদের ট্রেড লাইসেন্স প্রসেসিং, বাংলাদেশ নিরাপদ খাদ্য কর্তৃপক্ষ (BFSA) লাইসেন্স এবং কমার্শিয়াল কিচেন সেটআপের জন্য প্রয়োজনীয় মেন্টরশিপ ও দিকনির্দেশনা প্রদান করে থাকি।"
  },
  {
    "question": "বিদেশে শেফের চাকরি পেতে কী কী সার্টিফিকেট লাগে?",
    "seoAnswer": "বিদেশে শেফের চাকরি পেতে একটি NSDA-অনুমোদিত প্রফেশনাল কালিনারি সার্টিফিকেট, বিশ্বখ্যাত SGS-ISO ২২০০০ ফুড হাইজিন সার্টিফিকেট এবং HACCP ফুড সেফটি সার্টিফিকেট প্রয়োজন হয়। এগুলো বিদেশের কাজের ভিসা প্রসেসিং ও ট্রেড টেস্ট পাসের জন্য আইনিভাবে অত্যন্ত গুরুত্বপূর্ণ।",
    "fullAnswer": "বিদেশে, বিশেষ করে ইউরোপ, যুক্তরাজ্য এবং মধ্যপ্রাচ্যের উন্নত দেশগুলোতে প্রফেশনাল শেফ হিসেবে নিয়োগের জন্য প্রাতিষ্ঠানিক ও আইনি সনদের গুরুত্ব অপরিসীম। প্রথমত, আপনার একটি এনএসডিএ (NSDA) বা সরকারি বাংলাদেশ কারিগরি শিক্ষা বোর্ড (BTEB) অনুমোদিত ভোকেশনাল কালিনারি সার্টিফিকেট থাকতে হবে। দ্বিতীয়ত, আন্তর্জাতিক কিচেনগুলোতে কাজ করার জন্য অত্যন্ত গুরুত্বপূর্ণ দুটি ফুড সেফটি সনদ প্রয়োজন: ১. HACCP (Hazard Analysis Critical Control Point) সার্টিফিকেট এবং ২. ISO ২২০০০ ফুড সেফটি ম্যানেজমেন্ট সার্টিফিকেট, যা প্রমাণ করে আপনি বৈজ্ঞানিক পদ্ধতিতে খাবারকে জীবাণুমুক্ত রাখার নিয়ম জানেন। এই সার্টিফিকেটগুলো সুইজারল্যান্ডের এসজিএস (SGS) বা সমমানের স্বনামধন্য গ্লোবাল অডিট বডি দ্বারা প্রত্যয়িত হতে হয়। সিআইবি-র ৬ মাসের প্রোগ্রামে এই সমস্ত প্রয়োজনীয় সার্টিফিকেট অন্তর্ভুক্ত রয়েছে, যা আপনার সিভিক গ্লোবাল রিক্রুটারদের কাছে অত্যন্ত গ্রহণযোগ্য করে তোলে।"
  },
  {
    "question": "শেফ কোর্স শেষ করার পর JOB প্লেসমেন্ট আছে?",
    "seoAnswer": "হ্যাঁ, সিআইবি-র একটি ডেডিকেটেড ক্যারিয়ার প্লেসমেন্ট সেল রয়েছে। আমরা আমাদের শীর্ষ শিক্ষার্থীদের দেশের ৫-স্টার হোটেল ও প্রিমিয়াম রেস্তোরাঁয় ৪ মাসের বাধ্যতামূলক পেইড বা নন-পেইড ইন্টার্নশিপের সুযোগ করে দিই এবং পরবর্তীতে দেশে-বিদেশে স্থায়ী চাকরির ইন্টারভিউয়ের জন্য সাহায্য করি।",
    "fullAnswer": "কালিনারি ইনস্টিটিউট অব বাংলাদেশের একটি অত্যন্ত শক্তিশালী ও সফল ক্যারিয়ার প্লেসমেন্ট উইং রয়েছে। আমাদের কোর্স কারিকুলাম সফলভাবে সম্পন্ন করার পর, আমরা শিক্ষার্থীদের জন্য দেশের স্বনামধন্য ৫-স্টার হোটেল চেইন (যেমন রেনেসাঁ, সোনারগাঁও, ইন্টারকন্টিনেন্টাল) এবং প্রিমিয়াম গ্লোবাল চেইন রেস্টুরেন্টগুলোতে ইন্টার্নশিপের ব্যবস্থা করি। ইন্টার্নশিপ চলাকালীন শিক্ষার্থীদের কাজের শৃঙ্খলা, গতি এবং ব্যবহারিক যোগ্যতা ভালো থাকলে হোটেল কর্তৃপক্ষ তাদের সরাসরি স্থায়ী পদে নিয়োগ দিয়ে থাকে। এছাড়াও, আমরা আমাদের শিক্ষার্থীদের জন্য সিভি (CV) রাইটিং ওয়ার্কশপ, প্রফেশনাল কিচেন পোর্টফোলিও ভিডিও মেকিং, এবং মক ইন্টারভিউয়ের আয়োজন করি। আমাদের পার্টনার রিক্রুটিং এজেন্সিগুলোর মাধ্যমে আমরা মধ্যপ্রাচ্য ও ইউরোপের আন্তর্জাতিক চাকরির বিজ্ঞপ্তিগুলোতে সিআইবি গ্র্যাজুয়েটদের অগ্রাধিকার নিশ্চিত করতে সহায়তা করি, যাতে করে তাদের পেশাদার যাত্রা মসৃণ হয়।"
  },
  {
    "question": "শেফ হওয়ার জন্য কোন সাবজেক্টে ভালো হতে হবে?",
    "seoAnswer": "শেফ হওয়ার জন্য প্রাতিষ্ঠানিক কোনো কঠিন সাবজেক্টে ভালো হওয়ার প্রয়োজন নেই, তবে গণিতের প্রাথমিক ধারণা (কস্টিং ও পরিমাপের জন্য), ইংরেজি (যোগাযোগের জন্য) এবং বিজ্ঞানের প্রাথমিক ধারণা (ফুড কেমিস্ট্রি বোঝার জন্য) থাকলে সুবিধা পাওয়া যায়। সবচেয়ে বেশি প্রয়োজন একাগ্রতা ও কাজের প্রতি ভালোবাসা।",
    "fullAnswer": "রন্ধনশিল্প হলো বিজ্ঞান, গণিত এবং শিল্পের একটি অনন্য সমন্বয়। শেফ হওয়ার জন্য আপনাকে কোনো রকেট সায়েন্সে পিএইচডি করতে হবে না, তবে কিছু মৌলিক বিষয়ে সাধারণ ধারণা থাকলে কিচেনে ভালো করা সহজ হয়। যেমন: ১. গণিতের সাধারণ জ্ঞান: রেসিপি তৈরি করার সময় ইনগ্রেডিয়েন্টস সঠিক গ্রাম বা লিটারে পরিমাপ করতে এবং খাবারের কস্টিং হিসেব করতে প্রাথমিক যোগ-বিয়োগ-ভাগের প্রয়োজন হয়। ২. ইংরেজি: আন্তর্জাতিক রান্নাঘরের ভাষা ইংরেজি হওয়ায় রেসিপি বুক পড়া ও কিচেন ডিরেকশন বোঝার জন্য ইংরেজি খুবই সহায়ক। ৩. বিজ্ঞান: খাবার কীভাবে তাপে পরিবর্তিত হয়, প্রোটিন জমাট বাঁধা বা বেকিংয়ের সময় খামির ফুলে ওঠার পেছনের রন্ধন রসায়ন (Food Chemistry) বুঝতে বেসিক বিজ্ঞানের ধারণা কাজ দেয়। তবে সবার ওপরে যে গুণটি প্রয়োজন তা হলো—ধৈর্য, নিয়মানুবর্তিতা এবং দীর্ঘক্ষণ দাঁড়িয়ে কাজ করার শারীরিক মানসিক স্থায়িত্ব। আপনার যদি শেখার আগ্রহ থাকে, তবে সিআইবি-র প্রশিক্ষকরা আপনাকে বাকি সবকিছু শিখিয়ে নেবেন।"
  }
];

const enFaqs = [
  {
    "question": "What kind of job can I get after completing a chef course?",
    "seoAnswer": "After completing a chef course, you can secure positions like Commis Chef, Pastry Chef, or Demi Chef in 5-star hotels, luxury resorts, cruise lines, and premium restaurants. With 2-3 years of experience, you can promote to Chef de Partie or Sous Chef. You can also start a cloud kitchen or home bakery.",
    "fullAnswer": "Completing a professional culinary program unlocks vast employment opportunities in the global hospitality sector. In Bangladesh, graduates can apply for internships and full-time chef positions at leading 5-star hotel conglomerates such as Renaissance Dhaka, The Westin, Radisson Blu, and Pan Pacific Sonargaon. Typically, fresh graduates enter the kitchen hierarchy as Commis-III or Assistant Chefs, focusing on basic preparations and station mis-en-place. Over the next few years, based on culinary consistency, speed, and discipline, you can advance to Demi-CDP, Chef de Partie (CDP), and eventually Sous Chef or Executive Chef. Internationally, there is a massive shortage of certified chefs, particularly in the GCC region (Dubai, Riyadh, Doha) and European luxury hospitality networks, offering highly paid tax-free contracts with accommodation. Alternatively, graduates can leverage their costing and menu planning knowledge to launch successful food trucks, cafes, or home bakeries."
  },
  {
    "question": "How much does a chef course cost in Dhaka?",
    "seoAnswer": "The total course fee for the Professional Chef Course at CIB in Dhaka is 44,000 BDT. This covers all commercial ingredients, lab fees, study materials, and a professional chef kit (branded uniform, chef knife, and cutting board). A 3-installment option is available with no hidden charges.",
    "fullAnswer": "The cost of professional culinary education in Dhaka varies, but CIB Dhanmondi offers a premium, comprehensive 6-month Professional Chef Course for a total fee of 44,000 BDT. To make professional training accessible, we provide a flexible 3-stage installment plan. You pay an initial 16,000 BDT at enrollment to secure your seat. The remaining 28,000 BDT is split into two equal monthly installments of 14,000 BDT due at the end of the first and second months. Unlike many local culinary schools that charge separate fees for raw ingredients or exam sessions, CIB has a strict policy of zero hidden charges. The 44,000 BDT fee covers all premium ingredients (including salmon, imported cheese, and specialized herbs), your NSDA registration and assessment fees, and a professional chef kit consisting of a custom branded uniform, commercial cutting board, and a professional chef knife set."
  },
  {
    "question": "Which chef course is best for women?",
    "seoAnswer": "For women, CIB's 6-month Professional Chef Course and our short Baking & Pastry Arts course are highly recommended. We offer a safe, respectful, and CCTV-monitored co-educational environment. These courses prepare women for careers in commercial kitchens or to run home bakeries.",
    "fullAnswer": "Culinary arts has become a highly lucrative and empowering career path for women. At CIB, the 6-month Professional Chef Course and the specialized Baking & Pastry Arts Course are particularly popular among female students. CIB Dhanmondi prioritizes a safe, respectful, and modern co-educational learning environment. Our kitchen labs are fully CCTV-monitored, and we enforce a strict corporate code of conduct with zero tolerance for harassment. The hands-on nature of the training builds commercial kitchen stamina, preparing women to manage high-pressure hot kitchen stations or work in luxury hotels. For those seeking home-based financial independence, our baking course provides detailed training in recipe scaling, food hygiene, costing, and advanced cake decoration, allowing housewives to launch profitable custom cake shops or catering brands from their own kitchens with active CIB marketing guidance."
  },
  {
    "question": "How can I go abroad after doing a chef course?",
    "seoAnswer": "Complete an NSDA-accredited chef course to secure government and ISO-HACCP certifications. Build 1-2 years of working experience in local 3-5 star hotels. Clear basic English language requirements (or IELTS 5.5+ for Western countries) and apply through verified BMET-approved recruitment agencies.",
    "fullAnswer": "Securing employment abroad as a professional chef involves a structured, legally compliant path. First, acquire government-recognized vocational credentials, such as the NSDA Level-2 or 3 certificate, alongside international food safety credentials (ISO 22000 and HACCP) from CIB. Second, you must gain 1 to 2 years of practical, hands-on experience in a local 3 to 5-star hotel kitchen to build your speed and recipe consistency. Third, language proficiency is vital: while GCC countries only require conversational English, Western markets like the UK, Australia, and Canada require a minimum IELTS score of 5.5 or language certification (e.g., German A2/B1 for Germany's Skilled Worker visa). Finally, register on the Ami Probashi portal and apply through BMET-approved recruitment agencies. CIB's dedicated career placement cell actively guides graduates with CV writing, video cooking portfolio creation, and trade test preparation to ensure success."
  },
  {
    "question": "How long does it take to build a career as a chef?",
    "seoAnswer": "The foundational training takes 6 months (2 months of intensive practical kitchen lab classes + 4 months of 5-star hotel internship). However, establishing a strong career, mastering multiple kitchen sections, and promoting to senior roles like Chef de Partie or Sous Chef takes 3 to 5 years.",
    "fullAnswer": "Building a reputable culinary career is a progressive journey of skill acquisition. At CIB, your foundational journey takes 6 months: 2 months of intensive hands-on training in our commercial kitchen lab (held 3 days a week, 3 hours a day) followed by a 4-month on-the-job internship at a partner 5-star hotel. This 6-month phase qualifies you to start working as a Commis Chef. Transitioning from an entry-level cook to a competent Chef de Partie (CDP) who runs an entire station (like pastry, hot line, or cold larder) typically requires 3 to 4 years of active industry experience. Reaching the status of a Sous Chef or Executive Chef who manages budgets, menu engineering, and entire kitchen teams generally takes 5 to 8 years. Your growth speed is entirely determined by your discipline, culinary creativity, and continuous learning."
  },
  {
    "question": "What are the working hours of a chef?",
    "seoAnswer": "Professional chefs work in shifts, typically averaging 8 to 10 hours a day. Because hotels and restaurants operate 24/7, chefs rotate between morning, afternoon, and night shifts. Busy holiday seasons require extra dedication, which is rewarded with service charge bonuses.",
    "fullAnswer": "A chef's working schedule is dynamic and shift-based, reflecting the 24/7 operating nature of the hospitality sector. Standard shifts average 8 to 10 hours daily, and chefs rotate between morning shifts (typically 6:00 AM to 3:00 PM), afternoon/dinner shifts (2:00 PM to 11:00 PM), and occasional night or overnight prep shifts. The weekly off-day is rotating and may fall on a weekday. Holiday seasons, Ramadan, and large banqueting events represent high-pressure periods that demand longer hours, though they are compensated with overtime pay and higher service charge distributions. The environment is highly structured, requiring military-like coordination and rapid execution. CIB simulates this shift-work environment during intensive practical sessions to help students adapt to the physical demands of commercial kitchens."
  },
  {
    "question": "What documents are required for admission to a chef course?",
    "seoAnswer": "To enroll in a chef course at CIB, you need to submit copies of your educational certificates (SSC/HSC or equivalent), national identity card (NID) or digital birth registration, and 2 passport-sized color photos. No prior cooking experience or certificates are required.",
    "fullAnswer": "Admissions at the Culinary Institute of Bangladesh (CIB) follow a streamlined vocational enrollment process. To apply for our Professional Chef Course or any short-term specialty program, prospective students must submit: 1. A photocopy of their minimum SSC/HSC passing certificate or transcript (or any equivalent academic credential from any board). 2. A photocopy of their National Identity Card (NID) or digital Birth Registration Certificate. 3. Two recent passport-size color photographs. We do not require any past culinary experience, portfolios, or cooking certificates, as our training is designed to build skills from the ground up. Students from all streams (Science, Arts, Commerce, or Madrasah) are eligible. You can complete the process by visiting our Dhanmondi campus or submitting files online via our official portal."
  },
  {
    "question": "How long does it take to get a certificate after chef training?",
    "seoAnswer": "CIB's institutional completion certificate and transcript are issued within 7 to 10 days after your practical exam. However, the government-registered NSDA Level certificate takes 1 to 2 months from the assessment date due to national processing and board approvals.",
    "fullAnswer": "Receiving your professional certifications is a multi-step verification process. Immediately after completing your 2-month intensive kitchen lab and passing the practical examination, CIB issues your Institutional Certificate and Grade Sheet within 7 to 10 working days. Upon finishing your 4-month 5-star hotel internship, you will receive an official internship experience certificate directly from the hotel's HR department. For the government NSDA Level certification, students undergo a practical assessment evaluated by external government assessors at our campus. The processing, verification, and official print of these digital and physical NSDA certificates by the Prime Minister's Office board typically take 1 to 2 months. This government certificate is registered online, making it highly valuable for visa and immigration verification."
  },
  {
    "question": "Can a chef course be done online?",
    "seoAnswer": "A professional chef course cannot be completed entirely online because culinary arts is a practical, physical discipline. You must practice knife handling, temperature management, and flavor profile tuning in a commercial kitchen under the direct guidance of master chefs.",
    "fullAnswer": "While online cooking videos are useful for theoretical ideas, professional gastronomy requires physical, hands-on training that cannot be replicated through a screen. Crucial skills like safe knife control, precise vegetable cuts, tempura frying, baking dough consistency, and commercial oven safety must be practiced in a physical lab. CIB Dhanmondi provides every student with their own commercial workstation, allowing them to cook each recipe individually rather than in groups. This ensures you master the physical muscle memory required in a real kitchen. However, CIB does utilize hybrid models for our theoretical classes—such as food safety regulations (HACCP), menu design, food costing formulas, and hospitality English—which can be completed online for student convenience."
  },
  {
    "question": "Is accommodation available for students coming from outside Dhaka for a chef course?",
    "seoAnswer": "CIB does not operate its own hostels, but we provide full administrative support to students coming from outside Dhaka to help them find safe, affordable student housing, paying guest rooms, or shared messes near our Dhanmondi campus.",
    "fullAnswer": "We welcome students from all divisions of Bangladesh at CIB. While we do not have our own residential dormitories, our student welfare wing provides complete assistance in securing safe, clean, and affordable accommodation near the Dhanmondi and Kalabagan areas. There are numerous private student hostels, shared mess flats, and paying guest facilities within walking distance of our campus, with monthly rentals ranging from 3,000 to 6,000 BDT including basic meals. Our team provides verified contact details and pricing guides to make the transition smooth and safe for out-of-town students. Since classes are scheduled 3 days a week, many students successfully manage their schedules while living temporarily in Dhaka."
  },
  {
    "question": "What salary can be expected after a chef course?",
    "seoAnswer": "In Bangladesh, entry-level Commis Chefs start at 15,000-25,000 BDT plus service charge distributions. Experienced Chef de Parties earn 35,000-60,000 BDT, while international placements in GCC countries offer tax-free salaries ranging from 65,000 to 95,000 BDT monthly.",
    "fullAnswer": "Culinary compensation is directly linked to experience, certification, and specialization. In Bangladesh's 5-star hotel sector, a fresh graduate starts as a Commis-III with a base salary of 15,000 to 25,000 BDT. However, they also receive monthly service charge distributions, which can double their take-home pay. With 3-5 years of experience, a Chef de Partie (CDP) earns 35,000 to 60,000 BDT. Internationally, particularly in GCC countries (UAE, Saudi Arabia, Qatar), entry-level certified chefs receive tax-free salaries of 65,000 to 95,000 BDT, with employers covering visa, flights, health insurance, meals, and accommodation. Executive Chefs in Bangladesh's top hotels earn between 1,50,000 and 4,50,000 BDT monthly. CIB's premium training is designed to fast-track your path to these high-earning salary brackets."
  },
  {
    "question": "At what age should one start a chef course?",
    "seoAnswer": "The ideal age to start a chef course is between 16 and 35, as this period offers the best physical stamina and learning speed for commercial kitchens. However, there is no upper age limit, and CIB has successfully trained many students aged 40+.",
    "fullAnswer": "There is no strict age limit to pursue culinary arts, though the most common age bracket for starting a professional chef career is 16 to 35. This age range is ideal due to the physical nature of commercial kitchen work, which involves standing for long shifts and handling heavy equipment. Younger students also adapt quickly to knife skills, culinary English, and kitchen discipline. However, cooking is a lifelong passion. CIB regularly trains students in their 40s and 50s—including career switchers, retirees, and homemakers—who successfully complete our baking or cooking courses and go on to establish highly profitable home bakeries, catering companies, or restaurants. If you possess passion, discipline, and a willingness to learn, age is not a barrier."
  },
  {
    "question": "Is it essential to know English to become a chef?",
    "seoAnswer": "Yes, basic English is highly important. Commercial kitchens use English for recipe manuals, ingredients labeling, and classical French culinary terms. Furthermore, clearing basic English communication is essential for passing international job interviews and visa processing.",
    "fullAnswer": "While you don't need to be an expert in English literature, a basic working knowledge of English is essential for modern culinary success. Commercial kitchens globally operate in English. All standard recipe manuals, international menu items, safety labels, and classical French culinary terms (like julienne, chiffonade, mirepoix, or sauté) are written in English. Communication with international hotel guests, suppliers, and foreign Executive Chefs also requires basic English. For those aiming for skilled work visas in the UK, Canada, or Australia, passing an English proficiency test (like IELTS with a minimum 5.5 score) is mandatory. CIB provides bilingual instruction: we explain concepts in Bengali but enforce the use of correct culinary English terms to prepare you for global roles."
  },
  {
    "question": "How are the classes conducted in a chef course?",
    "seoAnswer": "CIB classes are highly structured and hands-on. Each 3-hour session begins with a brief theoretical review of the recipe and a live culinary demonstration by the mentor chef. Students then spend the remaining 2 hours cooking the dish individually at their own workstations.",
    "fullAnswer": "Classes at CIB are structured according to international vocational training standards. Each class is 3 hours long. The first 30 minutes consist of a briefing where the mentor chef explains the recipe's ingredients, culinary history, food science, and specific safety points. The next 30 minutes feature a live demonstration: the master chef cooks the dish, demonstrating proper knife cuts, cooking temperatures, and plating aesthetics. The final 2 hours are dedicated to student practice. Each student is assigned a commercial workstation with their own burner, oven, and raw ingredients. You cook the entire recipe individually, under the close supervision of our instructors. At the end of the class, the chef tastes and evaluates your dish on flavor balance, texture, and presentation, providing constructive feedback."
  },
  {
    "question": "Can the chef course fee be paid in installments?",
    "seoAnswer": "Yes. CIB offers a flexible 3-installment payment plan for the 44,000 BDT Professional Chef Course. You pay 16,000 BDT at admission to secure your seat, followed by two monthly installments of 14,000 BDT each. We accept cash, card, and mobile banking.",
    "fullAnswer": "We believe financial constraints should never prevent a talented student from acquiring high-value technical skills. To support our students, CIB offers a flexible 3-part installment plan for the 44,000 BDT Professional Chef Course, with no hidden interest or admin fees. You pay 16,000 BDT upon admission to confirm your slot and receive your chef kit. The second installment of 14,000 BDT is due at the end of the first month of classes, and the final 14,000 BDT is due at the end of the second month. We accept cash at our campus office, direct bank deposits, and mobile financial services (bKash, Nagad, Rocket) for easy remote payments, ensuring you can focus on mastering your culinary skills without financial stress."
  },
  {
    "question": "How is the practical training in a chef course?",
    "seoAnswer": "Over 95% of our curriculum is practical. CIB students train in state-of-the-art commercial kitchen labs, handling real premium ingredients (like fresh salmon, chicken, herbs, and sauces) individually. We do not use group cooking, ensuring every student masters the recipe.",
    "fullAnswer": "Culinary arts is a craft learned through practice, not reading. Over 95% of CIB's curriculum is hands-on. Our training labs are modeled after 5-star commercial hotel kitchens, equipped with commercial ranges, prep tables, and professional ovens. In every class, you are provided with your own portion of fresh ingredients—such as beef, salmon, seafood, cheese, and fresh herbs. Unlike other centers where students cook in groups, CIB requires every student to cook their own dish from start to finish. This builds the muscle memory and speed required in commercial operations. Our experienced instructors stand by your side to correct your knife angles, cooking temperatures, and plating techniques in real time."
  },
  {
    "question": "Can I start a restaurant business after doing a chef course?",
    "seoAnswer": "Yes. A chef course is the perfect foundation for opening a restaurant, cafe, or cloud kitchen. Besides cooking, CIB teaches critical business skills like portion control, food costing formulas, menu engineering, and kitchen design to prevent financial loss.",
    "fullAnswer": "Opening a food business is a lucrative venture if managed correctly. CIB's Professional Chef Course goes beyond teaching recipes; we prepare you for entrepreneurship. We teach critical kitchen business modules, including food costing formulas, portion sizing, inventory management, and menu engineering. Understanding these concepts helps you control food wastage, which is the leading cause of restaurant failures. Knowing how to run a kitchen also reduces your reliance on hired Head Chefs, preventing operational disruptions. CIB has helped numerous alumni launch successful restaurants, cafes, and cloud kitchens in Dhaka. We provide guidance on trade licenses, food safety registrations (BFSA), and kitchen layouts."
  },
  {
    "question": "What certificates are required to get a chef job abroad?",
    "seoAnswer": "To work abroad legally, you need an NSDA-accredited vocational certificate, a globally recognized ISO 22000 Food Safety Management certificate, and a HACCP (Hazard Analysis Critical Control Point) certificate. CIB's 6-month program includes all these mandatory credentials.",
    "fullAnswer": "International employers, particularly in Europe, UK, and the Middle East, legally require certified proof of skill and food safety compliance. The mandatory credentials include: 1. An accredited vocational certificate (such as the NSDA Level certificate from the Prime Minister's Office). 2. A HACCP (Hazard Analysis Critical Control Point) certificate, which proves you understand food safety hazard prevention. 3. An ISO 22000 Food Safety Management certificate. These certifications must be issued by or aligned with international auditing bodies like SGS Switzerland. Without these, your CV will be filtered out by HR systems. CIB's Professional Chef Course includes these certifications, validating your qualifications globally."
  },
  {
    "question": "Is there job placement assistance after completing a chef course?",
    "seoAnswer": "Yes. CIB has a dedicated Career Placement Cell that arranges a 4-month internship at partner 5-star hotels for top performing students. We also support graduates with CV writing, video portfolio creation, and connections to verified international recruiting agencies.",
    "fullAnswer": "CIB is committed to your employment success. Our dedicated Career Placement Cell works closely with graduates. After completing the 2-month practical training, we arrange a 4-month internship at leading partner 5-star hotels (like Renaissance, Radisson, InterContinental) for qualified students. A successful internship often leads directly to full-time employment at the hotel. We also conduct workshops on CV preparation, teach interview skills, and help students record high-quality cooking videos for their portfolios. Additionally, we connect alumni with government-approved recruiting agencies for job opportunities in the Gulf and Europe."
  },
  {
    "question": "Which subjects do I need to be good at to become a chef?",
    "seoAnswer": "You do not need to be an expert in any academic subject to become a chef. However, basic math is useful for recipe scaling and costing, basic English is important for international kitchens, and basic science helps you understand food chemistry. Passion and discipline are the most critical factors.",
    "fullAnswer": "Culinary arts is a practical combination of math, science, and creative art. You do not need an advanced academic degree, but basic skills in a few areas are helpful: 1. Basic Math: Necessary for scaling recipes (multiplying ingredients) and calculating food costing and portion sizes. 2. Basic English: Essential because international kitchen terms, recipe manuals, and equipment instructions are in English. 3. Basic Science: Helps you understand food chemistry, such as how heat changes proteins, how yeast works in bread, or how emulsions are formed in sauces. Above all, the most important requirements are physical stamina, discipline, attention to detail, and a passion for food. CIB's instructors will teach you all the necessary technical skills."
  }
];

function updateFaqFile(filePath, categoryName, newFaqs) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }

  const raw = fs.readFileSync(filePath, 'utf8');
  const data = JSON.parse(raw);
  
  // Find category
  const categoryIndex = data.categories.findIndex(c => c.category === categoryName);
  if (categoryIndex === -1) {
    console.error(`Category not found: ${categoryName} in ${filePath}`);
    return;
  }

  const currentFaqs = data.categories[categoryIndex].faqs;
  
  // Filter out any duplicate questions if they already exist
  const existingQuestions = new Set(currentFaqs.map(f => f.question.toLowerCase().trim()));
  const faqsToAdd = newFaqs.filter(f => !existingQuestions.has(f.question.toLowerCase().trim()));
  
  data.categories[categoryIndex].faqs = [...currentFaqs, ...faqsToAdd];
  
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${filePath}. Added ${faqsToAdd.length} FAQs to "${categoryName}".`);
}

const bnPath = path.join(__dirname, '../content/bn/faq.json');
const enPath = path.join(__dirname, '../content/en/faq.json');

updateFaqFile(bnPath, "কণ্ঠস্বর অনুসন্ধান (ভয়েস সার্চ)", bnFaqs);
updateFaqFile(enPath, "Conversational Voice Queries", enFaqs);
